modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"

[[mods]]
    modId="melatowoin"
    version="${version}"
    displayName="Create: MelatOwOin"
    description='''
        Cat ears, chloroform, and other Create-powered chaos.
    '''
    logoFile="assets/melatowoin/icon.png"
    authors="Cloveian"

[[dependencies.melatowoin]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.melatowoin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.melatowoin]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.melatowoin]]
    modId="architectury"
    mandatory=true
    versionRange="[9.2.14,)"
    ordering="NONE"
    side="BOTH"
